# Generated by Django 4.2.2 on 2023-07-03 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
