# Generated by Django 4.2.2 on 2023-07-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='word_id',
        ),
    ]
