# Generated by Django 4.2.2 on 2023-07-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_remove_progress_user_id_remove_progress_word_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='word_id',
            field=models.IntegerField(default=0),
        ),
    ]
